SchoolSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('trainer/', include('trainer.urls')),
    path('courses/', include('courses.urls')), 
    path('events/', include('events.urls')),
    path("", include("core.urls")),
    path("api/", include("api.urls")),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/urls.py
from django.db import router
from django.urls import path, include
from rest_framework import routers, urlpatterns
from .views import EventViewSet, StudentViewSet
from .views import TrainerViewSet
from .views import CourseViewSet

router = routers.DefaultRouter()
router.register("students/", StudentViewSet)
router.register("trainers/", TrainerViewSet)
router.register("courses/", CourseViewSet)
router.register("events/", EventViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls)),
]

events/urls.py
from django.conf.urls import url
from .import views
app_name = 'cal'

urlpatterns = [  
    url(r'^index/$', views.index, name='index'),
    url(r'^cal/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),  
]

events/models.py
from django.conf.urls import url
from django.db import models
import datetime
from django.urls import reverse

# Create your models here.
class Events(models.Model):
    event_name=models.CharField(max_length=12)
    event_location=models.CharField(max_length=10)
    start_time = models.DateTimeField(default=datetime.date.today)
    end_time = models.DateTimeField(default=datetime.date.today)

def __str__(self):
    return self.event_name

@property
def get_htm_url(self):
    url = reverse('event_edit', args=(self.id,))
    return f'<p>{self.event_name}</p><a href="{url}">edit</a>'

events/forms.py
from django import forms
from django.forms.widgets import DateInput, TextInput
from.models import Events
from django.forms import fields

class EventRegistrationForm(forms.ModelForm):
    class Meta:
        model =Events
        fields="__all__"
        widgets = {
      'start_time': DateInput(attrs=
      {
        'type': 'datetime-local',
        'style': 'max-width: 300px;',
        'class': "form-control",
      }, 

      format='%Y-%m-%dT%H:%M'),

      'end_time': DateInput(attrs=
      {
        'type': 'datetime-local',
        'style': 'max-width: 300px;',
        'class': "form-control",    
      },
       
      format='%Y-%m-%dT%H:%M'),

      'event_name':TextInput(attrs=
      {
        'class': "form-control",
        'style': 'max-width: 300px;',
        'placeholder': 'Name'
      }),

      'event_location':TextInput(attrs=
      {
        'class': "form-control",
        'style': 'max-width: 300px;',
        'placeholder': 'Event Venue'
      }),     
    }

    def __init__(self, *args, **kwargs):
        super(EventRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

events/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar

from .models import *
from .utils import Calendar
from .forms import EventRegistrationForm
# Create your views here.


def index(request):
    return HttpResponse('hello')

class CalendarView(generic.ListView):
    model = Events
    template_name = 'cal/calendar.htm'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    instance = Events()
    if event_id:
        instance = get_object_or_404(Events, pk=event_id)
    else:
        instance = Events()

    form = EventRegistrationForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/events.htm', {'form': form})




# def register_event(request):
#     if request.method=="POST":
#         form=EventRegistrationForm(request.POST,request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('register_event')
#         else:
#             print(form.errors)
#     else:
#         form=EventRegistrationForm()
#     return render(request,"register_event.htm", {"form":form})

# def event_list(request):
#     events = Events.objects.all()
#     return render(request, "event_list.htm", {"events":events})

events/templates/cal/base.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Font Awesome -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

  <!-- MDB -->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/style.css' %}">

<title>Calender</title>
</head>
<body>
  <style>
/* Common styles */
body {
  font-family: "ptsans", "Lato", "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.info {
  border-color: #c200a8;
  color:#c200a8;
}
  
.info:hover {
  background:#c200a8;
  color: white;
}

.info {
  border-color: #c200a8;
  color:#c200a8;
}

.info:hover {
  background:#c200a8;
  color: white;
}

.container {
  margin-top: 10px;
  background-color: white;
  margin-left: 30%;
  width: 500px;
  border:3px solid #c200a8;
  box-shadow: 8px 8px 8px 9px #c200a8;
  border-radius: 10px;
}

button{
  background-color:#ffffff;
  color:#c200a8;
  border-radius: 10px;
  padding: 10px;
  align-items: center;
  width: 300px;
  margin-right: 71px;
}

h1{
  padding-top: 10px;
  color:#000000;
  margin-left: 100px;
}

p{
  color: #c200a8;
}

form{
  padding-top: 20px;
  padding-left: 80px;
  padding-bottom: 20px;
}

.form-group{
  border-color: #c200a8;
}

hr{
  background-color:#c200a8;
  height: 3px;
}

.left {
  float: left;
}

.right {
  float: right;
}

.clearfix {
  margin: 15px;
}





/* App styles */
.title {
  text-align: center;
  margin: 10px;
}

.calendar {
  width: 58%;
  margin-left: 25%;
  font-size: 13px;
}


.calendar tr, .calendar td {
  border: 1px solid #c200a8;
}


.calendar th {
  padding: 10px;
  text-align: center;
  font-size: 18px;
}

.calendar td {
  width: 100px;
  height: 50px;
  padding: 20px 0px 0px 5px;
}


.month {
  font-size: 25px;
}

.date {
  font-size: 16px;
}

ul {
  height: 100%;
  padding: 0px 5px 0px 20px;
}

a {
  color:#c200a8;
}
textarea{
  width: 100%;
}
  </style>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  <hr>

  {% block content %}
  {% endblock %}
<!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

events/templates/cal/calendar.htm
{% extends 'cal/event_list.htm' %}

{% block title %}
Events Calendar
{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn info" href="{% url 'cal:event_new' %}"> Add Event </a>
</div>
{{ calendar }}
{% endblock %}

events/templates/cal/event_list.htm
{% extends 'cal/base.htm' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn info" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!DOCTYPE html>
<html lang="en">

<body>
<style>
    </style>
<div class="container">
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" class="register"> Submit </button>
</form>
</div>
</body>
</html>
{% endblock %}

events/templates/cal/events.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Details</title>
<style>
    
    body{
        margin:0;
        font-family:arial,tahoma,sans-serif;
        font-size:12px;
        font-weight:normal;
        direction:ltr;
        background:#FBD5F1;
        background-repeat: no-repeat;
        }
     .registration{
        /* margin:10% auto 0 auto; */
        padding:30px;
        width:400px;
        height:auto;
        overflow:hidden;
        background:#f3c4e6;
        border-radius:20px;
       margin: auto;
              }
    .registration:hover{
        background: rgba(255, 255, 255, 0.659);
              }
        button{
             
         background-color: #f75dce;
         width: 25%;  
          color: rgb(255, 255, 255); 
          font-size: 16px;  
          font-weight: bolder;
          padding: 15px;   
          margin: 10px 0px;   
          border: none;   
          cursor: pointer; 
          border-radius: 10px;  
         }
         button:hover {   
          opacity: 0.7; 
          background: none;  
          border: solid 1px #f75dce;
          color: black;
      }  
        input{
               width: 100%;
               outline: none;
             
               font-size: 15px;
               padding: 8px 8px;
               border-radius: 40px;
               transition: all 0.3 ease;
               background-color: white;
               border: solid 1px #f75dce;
           }
           select{
               -webkit-appearance: none;
                appearance: none;
                width: 100%;
               outline: none;
              font-size: 15px;
               padding: 8px 8px;
               border-radius: 40px;
               transition: all 0.3 ease;
               background-color: white;
               border: solid 1px #f75dce;
           }
           hr{
              border-top: 1px dashed #f75dce;
           }
    </style>
</head>
<body>
    

    <center><h1>Registration Details</h1></center>
    
    <div class="registration">
        <form method="POST" enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}  
            <button type="submit" class="sign-up-btn">Submit</button>  
        </form>
        
    </div>   
</body>
</html>

events/templates/cal/register_event.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration Details</title>
<style>
    ::-webkit-scrollbar {
    width: 10px;
}
::-webkit-scrollbar-track {
    background:white;
}
::-webkit-scrollbar-thumb {
    background: #c20098;
    border-radius: 30px;
}

::-webkit-scrollbar-thumb:hover {
    background:#c200a2;
}
     body{
        margin:0;
        font-family:arial,tahoma,sans-serif;
        font-size:12px;
        font-weight:normal;
        direction:ltr;
        background:#FBD5F1;
        background-repeat: no-repeat;
        }
     .reg{
        /* margin:10% auto 0 auto; */
        padding:30px;
        width:400px;
        height:auto;
        overflow:hidden;
        background:#f3c4e6;
        border-radius:20px;
       margin: auto;
              }
    .reg:hover{
        background: rgba(255, 255, 255, 0.659);
              }
        button{
             
         background-color: #f75dce;
         width: 25%;  
          color: rgb(255, 255, 255); 
          font-size: 16px;  
          font-weight: bolder;
          padding: 15px;   
          margin: 10px 0px;   
          border: none;   
          cursor: pointer; 
          border-radius: 10px;  
         }
         button:hover {   
          opacity: 0.7; 
          background: none;  
          border: solid 1px #f75dce;
          color: black;
      }  
        input{
               width: 100%;
               outline: none;
             
               font-size: 15px;
               padding: 8px 8px;
               border-radius: 40px;
               transition: all 0.3 ease;
               background-color: white;
               border: solid 1px #f75dce;
           }
           select{
               -webkit-appearance: none;
                appearance: none;
                width: 100%;
               outline: none;
              font-size: 15px;
               padding: 8px 8px;
               border-radius: 40px;
               transition: all 0.3 ease;
               background-color: white;
               border: solid 1px #f75dce;
           }
           hr{
              border-top: 1px dashed #f75dce;
           }

    </style>
</head>
<body>
    

    <center><h1>Registration Details</h1></center>
    
    <div class="registration">
        <form method="POST" enctype="multipart/form-data">
            {%csrf_token%}
            {{form.as_p}}  
            <button type="submit" class="sign-up-btn">Submit</button>  
        </form>
        
    </div>   
</body>
</html>