SchoolSystem/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls')),
    path('trainer/', include('trainer.urls')),
    path('courses/', include('courses.urls')), 
    path('events/', include('events.urls')),
    path("", include("core.urls")),
    path("api/", include("api.urls")),


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

api/urls.py
from django.db import router
from django.urls import path, include
from rest_framework import routers, urlpatterns
from .views import EventViewSet, StudentViewSet
from .views import TrainerViewSet
from .views import CourseViewSet

router = routers.DefaultRouter()
router.register("students/", StudentViewSet)
router.register("trainers/", TrainerViewSet)
router.register("courses/", CourseViewSet)
router.register("events/", EventViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls)),
    path("", include(router.urls)),
]

core/urls.py
from core.views import home
from django.conf.urls import include
from django.urls.conf import path



urlpatterns = [
path("", home, name="home_page"),
]

events/urls.py
from django.conf.urls import url
from .import views
app_name = 'cal'

urlpatterns = [  
    url(r'^index/$', views.index, name='index'),
    url(r'^cal/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),  
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from datetime import date
from events.models import Events
from typing import Counter
from student.models import Student
from django.shortcuts import render
from student.models import Student
from trainer.models import Trainer
from courses.models import Courses

# Create your views here.

def home(request):
    student=Student.objects.count()
    trainer=Trainer.objects.count()
    courses=Courses.objects.count()
    events=Events.objects.count()

    data = {"student": student, "trainer": trainer, "course": courses ,"events":events}
    return render(request, "home_page.htm", data)

core/templates/home_page.htm
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Document</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: "Poppins", sans-serif;
}

body {
    background: #F6F9FF;
    height: 100vh;
    width: 100%;

    display: flex;
    justify-content: center;
    align-items: center;

    color: #434343;

    font-size: 16px;
}

main.cards {
    display: flex;
    padding: 32px;
}

main.cards section.card {
    display: flex;
    flex-direction: column;
    align-items: center;
    text-align: center;
    background: white;
    padding: 1rem 1.5rem;
    border-radius: 8px;
    max-height: 468px;
    margin-left: 32px;
}

main.cards section.card:first-child {
    margin-left: 0;
}

main.cards section.card .icon {
    width: 64px;
    height: 64px;
}

main.cards section.card img {
    width: 100%;
}

main.cards section.card h3 {
    font-size: 100%;
    margin: 16px 0;
}

main.cards section.card span {
    font-weight: 300;
    max-width: 240px;
    font-size: 80%;
    margin-bottom: 16px;
}

main.cards section.card button {
    padding: 0.5rem 1rem;
    text-transform: uppercase;
    border-radius: 32px;
    border: 0;
    cursor: pointer;
    font-size: 80%;
    font-weight: 500;
    color: #fff;
    margin-bottom: 16px 0;
}

main.cards section.card.contact button {
    background: linear-gradient(to right, #9F66FF, #DFCBFF);
}
main.cards section.card.shop button {
    background: linear-gradient(to right, #3E8AFF, #BBDEFF);
}
main.cards section.card.about button {
    background: linear-gradient(to right, #FE5F8F, #FFC7D9);
}

main.cards section.card.contact {
    box-shadow: 20px 20px 50px -30px #DBC4FF;
}
main.cards section.card.shop {
    box-shadow: 20px 20px 50px -30px #AFD6FF;
}
main.cards section.card.about {
    box-shadow: 20px 20px 50px -30px #FFC1D5;
}

@media screen and (max-width: 720px) {
    main.cards {
        flex-direction: column;
    }

    main.cards section.card {
        margin-left: 0;
        margin-bottom: 32px;
    }

    main.cards section.card:last-child {
        margin-bottom: 0;
    }

    main.cards section.card button {
        font-size: 70%;
    }

}

h2{
  padding-left: 20px;
}

::-webkit-scrollbar {
    width: 10px;
}
::-webkit-scrollbar-track {
    background:white;
}
::-webkit-scrollbar-thumb {
    background: #c20098;
    border-radius: 30px;
}

::-webkit-scrollbar-thumb:hover {
    background:#c200a2;
}



.sidebar {
  height: 100%;
  width: 160px;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: #f8a7e2;
  overflow-x: hidden;
  padding-top: 16px;
}

.sidebar a {
  padding: 20px;
  text-decoration: none;
  font-size: 20px;
  color: #000000;
  display: block;
}

.sidebar a:hover {
  color: #f1f1f1;
}



 

</style>
</head>
<body>

<div class="sidebar">
  <center> <h1>C <span> Q</span></h1> </center>
  <a href="#home"><i class="fa fa-fw fa-home"></i> Home</a>
  <a href="#student"><i class="fa fa-fw fa-graduation-cap"></i> Students</a>
  <a href="#trainers"><i class="fa fa-fw fa-user"></i> Trainers</a>
  <a href="#courses"><i class="fa fa-fw fa-book"></i> Courses</a>
  <a href="#events"><i class="fa fa-fw fa-calendar"></i> Events</a>

</div>
<!-- <img src="https://www.academyfront.com/images/blog/school-software.png" alt=""> -->

<main class="cards">
  <section class="card contact">
      <div class="icon">
          <img src="https://www.pngitem.com/pimgs/m/235-2350916_student-netid-login-transparent-background-student-icon-hd.png" alt="Students.">
      </div>
      <h3>Students.</h3>
      <button>{{student}} Students</button>
  </section>
  <section class="card shop">
      <div class="icon">
          <img src="https://websites.ucr.edu/sites/g/files/rcwecm301/files/styles/form_preview/public/education-icon.png?itok=y0rzpT_2" alt="Trainers.">
      </div>
      <h3>Trainers.</h3>
      <button>{{trainer}} Trainers</button>
  </section>
  <section class="card about">
      <div class="icon">
          <img src="https://i.pinimg.com/originals/49/80/d7/4980d751d522ce2eb66e28c45ced8ed0.jpg" alt="Courses.">
      </div>
      <h3>Courses.</h3>
      <button>{{course}} Courses</button>
  </section>
  <section class="card about">
    <div class="icon">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeP6yFfPwCEiawAI_GuX4xLgiAzbZ3he7LiA&usqp=CAU" alt="Events.">
    </div>
    <h3>Events.</h3>
    <button>{{events}} Events</button>
</section>
</main>


</body>
</html> 

    
     <!-- <nav class="navbar">
        <div class="max-width">
            <div class="logo"><a href="#">C<span>Q</span></a></div>
            
            <ul class="menu">
                <li><a href="{%url 'home_page'%}" class="menu-btn">Home</a></li>

                <li><a href="{%url 'student_list'%}"class="menu-btn">Students</a></li>
                <li><a href="{%url 'trainer_list'%}"class="menu-btn">Trainers</a></li>
                <li><a href="{%url 'course_list'%}"class="menu-btn">Courses</a></li>
               <li><a href="{%url 'cal:calendar'%}"class="menu-btn">Events</a></li>
            </ul>
            <div class="menu-btn">
                <i class="fas fa-bars"></i>
            </div>
        </div>
    </nav>

    <!-- home section start -->
    <!-- <section class="home" id="home">
        
        <div class="max-width">
            <div class="home-content"> 
             
               <h2 class="text-2">Code Queen School System</h2> 
                    <button class="student">{{student}} Students</button>
                    <button class="trainer">{{trainer}} Trainers</button>    
                    <button class="course">{{course}} Courses</button>
                    <button class="events">{{events}} Events</button>

                    
                
                    
              
            </div>
            <div class="left">
                <img src="https://satmatgroup.com/school_management_software/bootstrap/image/why_school_management_software_opt.png" alt="image">
            </div> -->
        <!-- </div>  -->
        

<!-- <img src="https://satmatgroup.com/school_management_software/bootstrap/image/why_school_management_software_opt.png" alt="image"> -->